name: dpdk
version: '17.11'
summary: DPDK is a set of libraries and drivers for fast packet processing.
description: DPDK is a set of libraries and drivers for fast packet processing. 
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  dpdk:
    plugin: dump
    stage-packages:
      - dpdk
      - libc6

#passthrough:
  #layout:
   #/usr:
    #bind: $SNAP/usr
   #/etc:
    #bind: $SNAP/etc
   #/lib:
    #bind: $SNAP/lib
   #/sbin:
    #bind: $SNAP/sbin
    
apps:
  testpmd:
    command: usr/bin/testpmd
  dpdk-pdump:
    command: usr/bin/dpdk-pdump
  dpdk-pmdinfo: 
    command: usr/bin/dpdk-pmdinfo
  dpdk-procinfo: 
    command: usr/bin/dpdk-procinfo
  dpdk-test-crypto-perf:
    command: usr/bin/dpdk-test-crypto-perf
  dpdk-test-eventdev: 
    command: usr/bin/dpdk-test-eventdev
  dpdk-devbind: 
    command: sbin/dpdk-devbind
  dpdk-init:
    command: lib/dpdk/dpdk-init start
    daemon: simple
