name: dpdk
version: '17.11'
summary: DPDK is a set of libraries and drivers for fast packet processing.  
description: DPDK is a set of libraries and drivers for fast packet processing. 
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
#icon: doc/logo/DPDK_logo_vertical_rev_small.png

parts:
  dpdk:
    plugin: python
    python-version: python3
    source: git://dpdk.org/dpdk
    source-type: git
    source-tag: v17.11 # LTS Version, comment out or change tag to what version you require. 
    build-packages:
      - linux-headers-4.15.0-20-generic # Change to the kernel you need
      - build-essential 
      - libnuma-dev
      - pkg-config
      - libelf-dev
    stage-packages:
      - libc6
    override-build: |
      snapcraftctl build
      make install T=x86_64-native-linuxapp-gcc DESTDIR=$SNAPCRAFT_PART_INSTALL/dpdk

apps:
  dpdk-pdump:
    command: dpdk/bin/dpdk-pdump
  dpdk-pmdinfo:
    command: dpdk/bin/dpdk-pmdinfo
  dpdp-procinfo:
    command: dpdk/bin/dpdk-procinfo
  dpdk-test-crypto-perf:
    command: dpdk/bin/dpdk-test-crypto-perf
  dpdk-test-eventdev:
    command: dpdk/bin/dpdk-test-eventdev
  testpmd:
    command: dpdk/bin/testpmd
  dpdk-devbind:
    command: dpdk/sbin/dpdk-devbind
